### ISSUE TITLE
Dependencies not statisfied : yunohost (2.6.4) should be  >> 2.6.4

### ISSUE THREAD

**Issue by raphaeljolivet** [YunoHost-Apps/turtl_ynh#3]
Hi, 

I am unable to install it on yunohost 2.6.4.
I says it should be 2.6.4 : which is the case ....

**Comment by ldidry** [comment]
Mmh, `>>` seems to me that it wants a superior version.

Confirmed by the documentation: https://yunohost.org/#/packaging_apps_manifest_fr

**Comment by raphaeljolivet** [comment]
I just ran "system update" and though it would get me the last version.
Is there a newer version than that ?
How to upgrade ?

**Comment by raphaeljolivet** [comment]
Ok sorry, nevermid : 
https://yunohost.org/#/update
